required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd/mockery",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
