// Code generated by mockery v1.0.0. DO NOT EDIT.

package hashmap

import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *MockStorage) Delete(key Key) {
	_m.Called(key)
}

// Get provides a mock function with given fields: key
func (_m *MockStorage) Get(key Key) (interface{}, bool) {
	ret := _m.Called(key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(Key) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(Key) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Iterate provides a mock function with given fields: handler
func (_m *MockStorage) Iterate(handler Handler) bool {
	ret := _m.Called(handler)

	var r0 bool
	if rf, ok := ret.Get(0).(func(Handler) bool); ok {
		r0 = rf(handler)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *MockStorage) Set(key Key, value interface{}) {
	_m.Called(key, value)
}
